### ISSUE TITLE
New Setup Errors

### ISSUE THREAD

**Issue by ky13d3nt0n** [feedernet/petnet-feeder-service#61] opened 2021-02-15 04:23 UTC
Had to rebuild my petnet-feeder-service instance today and ran into some issues settings things back up again. 

Issues
- New Feeder setup would not dispense for weighing.
- Not able to update settings of feeders. 
- Getting 400 errors for `/telemetry` (using sample nginx.conf)

<img width="1157" alt="Screen Shot 2021-02-14 at 23 11 36" src="https://user-images.githubusercontent.com/52417040/107904595-46a54080-6f1a-11eb-8f2a-25caa068b3ef.png">

<img width="1278" alt="Screen Shot 2021-02-14 at 23 10 45" src="https://user-images.githubusercontent.com/52417040/107904629-5e7cc480-6f1a-11eb-8e89-8ca018712fd1.png">

Attempted Remedies
- Deleted DB
- Rebuilt containers
- Removed all docker containers and images
- Re-flashed RPI SD card

**Comment by mbillow** [comment] 2021-02-15 04:44
I noticed restarting your feeders wasn’t on the list of steps you took. Have you tried that?

Anecdotally, I think they may sometimes take a restart to start using new MQTT authentication keys. This definitely sounds like the feeders are registering themselves but not connecting to the broker.

**Comment by mbillow** [comment] 2021-02-15 04:45
Also, this ticket has made me realize we need an issue template that has an optional cat picture section. There is no better motivation to fix issues than a cute cat who just wants to eat! 🤣

**Comment by mbillow** [comment] 2021-02-15 05:47
Oof, actually, this is likely us just ignoring MQTT messages from the feeders. I’ll do some testing a put out a fix early this week.

**Comment by ky13d3nt0n** [comment] 2021-02-15 17:02
@mbillow thanks for your quick response!

At one point I did try switching the feeders off and back on again...but I was also deleting the DB, killing the docker containers and resetting them all to troubleshoot so I may just done things in an incorrect order.

The feeders seem to be dispensing on their previous schedules so no starving kitties. Lol.

I checked the app this morning and the feeders are still showing and it's keeping track of what meals have been dispensed, but there's no history and it's saying feeders no longer connected

Also included the kitties to help motivate! Lol
![Screen Shot 2021-02-15 at 11 57 46](https://user-images.githubusercontent.com/52417040/107975070-881f0580-6f85-11eb-898f-4d161046c294.png)

**Comment by jordan-hamilton** [comment] 2021-02-16 17:46
Hey there,

If it's helpful, I'm noticing something similar to what @ky13d3nt0n described after setting up as well as restarting the feeder - the below messages just repeat in the Docker logs. Let me know if I can clarify anything or assist!

```petnet-feeder-service    | 2021-02-16 17:36:38,053   INFO     uvicorn.access: 172.20.0.2:34044 - "POST /api/v1/kronos/gateways HTTP/1.0" 200
nginx                    | 10.0.0.18 - - [16/Feb/2021:17:36:38 +0000] "POST /api/v1/kronos/gateways HTTP/1.1" 200 92 "-" "IOE Client" "-"
petnet-feeder-service    | 2021-02-16 17:36:39,935   INFO     uvicorn.access: 172.20.0.2:34046 - "GET /api/v1/kronos/gateways/[...]/config HTTP/1.0" 200
nginx                    | 10.0.0.18 - - [16/Feb/2021:17:36:39 +0000] "GET /api/v1/kronos/gateways/[...]/config HTTP/1.1" 200 173 "-" "IOE Client" "-"
petnet-feeder-service    | 2021-02-16 17:36:42,038   INFO     uvicorn.access: 172.20.0.2:34048 - "POST /api/v1/kronos/devices HTTP/1.0" 200
nginx                    | 10.0.0.18 - - [16/Feb/2021:17:36:42 +0000] "POST /api/v1/kronos/devices HTTP/1.1" 200 163 "-" "IOE Client" "-"
petnet-feeder-service    | 2021-02-16 17:36:43,036   INFO     hbmqtt.broker: Listener 'tcp-ssl-1': 12 connections acquired
petnet-feeder-service    | 2021-02-16 17:36:43,036   INFO     hbmqtt.broker: Connection from 10.0.0.18:63832 on listener 'tcp-ssl-1'
petnet-feeder-service    | 2021-02-16 17:36:43,325   WARNING  hbmqtt.broker: Client [...] is already connected, performing take-over.
petnet-feeder-service    | 2021-02-16 17:36:53,347   ERROR    root: Caught global exception:
petnet-feeder-service    | Traceback (most recent call last):
petnet-feeder-service    |   File "/usr/local/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
petnet-feeder-service    |     raise exceptions.TimeoutError()
petnet-feeder-service    | asyncio.exceptions.TimeoutError
petnet-feeder-service    | 2021-02-16 17:36:53,349   ERROR    root: Caught global exception:
petnet-feeder-service    | Traceback (most recent call last):
petnet-feeder-service    |   File "/usr/local/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
petnet-feeder-service    |     raise exceptions.TimeoutError()
petnet-feeder-service    | asyncio.exceptions.TimeoutError
petnet-feeder-service    | 2021-02-16 17:36:53,352   ERROR    root: Caught global exception:
petnet-feeder-service    | Traceback (most recent call last):
petnet-feeder-service    |   File "/usr/local/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
petnet-feeder-service    |     raise exceptions.TimeoutError()
petnet-feeder-service    | asyncio.exceptions.TimeoutError
petnet-feeder-service    | 2021-02-16 17:36:53,354   ERROR    root: Caught global exception:
petnet-feeder-service    | Traceback (most recent call last):
petnet-feeder-service    |   File "/usr/local/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
petnet-feeder-service    |     raise exceptions.TimeoutError()
petnet-feeder-service    | asyncio.exceptions.TimeoutError
petnet-feeder-service    | 2021-02-16 17:36:53,356   ERROR    root: Caught global exception:
petnet-feeder-service    | Traceback (most recent call last):
petnet-feeder-service    |   File "/usr/local/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
petnet-feeder-service    |     raise exceptions.TimeoutError()
petnet-feeder-service    | asyncio.exceptions.TimeoutError
petnet-feeder-service    | 2021-02-16 17:36:53,358   ERROR    root: Caught global exception:
petnet-feeder-service    | Traceback (most recent call last):
petnet-feeder-service    |   File "/usr/local/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
petnet-feeder-service    |     raise exceptions.TimeoutError()
petnet-feeder-service    | asyncio.exceptions.TimeoutError
petnet-feeder-service    | 2021-02-16 17:36:53,360   ERROR    root: Caught global exception:
petnet-feeder-service    | Traceback (most recent call last):
petnet-feeder-service    |   File "/usr/local/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
petnet-feeder-service    |     raise exceptions.TimeoutError()
petnet-feeder-service    | asyncio.exceptions.TimeoutError

**Comment by mbillow** [comment] 2021-02-16 18:32
Free PR for anyone who has electricity and reverses this commit. 

https://github.com/feedernet/petnet-feeder-service/commit/ba2e01802aa26bb117acced79e4b3b0be2045589

**Comment by kruton** [comment] 2021-02-16 19:11
I can revert this. I'm not convinced it will solve the problems, though.

**Comment by mbillow** [comment] 2021-02-21 17:37
@ky13d3nt0n @jordan-hamilton Can you pull the latest image and try this again? I can confirm that my feeders are working as intended now.

**Comment by ky13d3nt0n** [comment] 2021-02-21 19:17
@mbillow yep, can confirm this is working! I'm able to manually dispense food and change settings on both feeders.

Sidenote, would love to put in a feature request for updating the application or at least some documentation on steps to properly update. I'm not the greatest with docker so I stopped and removed my existing containers and then to update I just did:
`docker-compose up` followed by a `docker-compose up -d`.

**Comment by mbillow** [comment] 2021-02-21 21:40
The shortest route using compose is likely `docker-compose pull` and then `docker-compose up -d`. Compose is smart enough to recreate the container when it sees a newer image. If you want to make a new issue for this, we can definitely get some documentation out about how to do both the Docker and manual update process (pulling new changes, running migrations, etc.).

**Comment by jordan-hamilton** [comment] 2021-02-21 23:29
Thanks for checking, @mbillow! Mine is also working after pulling the latest image.

**Comment by mbillow** [comment] 2021-02-21 23:40
Awesome! 😎 

Sorry it was broken, feel free to blame my laziness in not actually testing that change with real feeders. 🥴

Closing this out.

**Closed by mbillow** 2021-02-21 23:40 UTC
Labels: bug
