### ISSUE TITLE
Unable to launch the docker container

### ISSUE THREAD

**Issue by xoengine** [feedernet/petnet-feeder-service#40] opened 2021-01-01 16:57 UTC
Following the directions in the wiki. Full disclaimer, I'm new to docker and git so probably something I'm doing wrong.  Any guidance or help would be appreciated.

Using Raspberry Pi 3 Model B Rev 1.2

pi@raspberrypi:/petnet-feeder-service $ sudo docker-compose logs petnet-feeder-service
ERROR: No such service: petnet-feeder-service
pi@raspberrypi:/petnet-feeder-service $ 

I edited the docker-compose-yml and added "petnet-" to the service

services:
  petnet-feeder-service:

**not sure if this is the correct thing to do but get past that error.**

pi@raspberrypi:/petnet-feeder-service $ sudo docker-compose start -d petnet-feeder-service
Start existing containers.

Usage: start [SERVICE...]
pi@raspberrypi:/petnet-feeder-service $ 

**looking at the docker compose logs I get this** 

pi@raspberrypi:/petnet-feeder-service $ sudo docker-compose logs petnet-feeder-service
Attaching to 
pi@raspberrypi:/petnet-feeder-service $

pi@raspberrypi:/petnet-feeder-service $ sudo docker-compose --verbose logs petnet-feeder-service
compose.config.config.find: Using configuration files: ./docker-compose.yaml
docker.utils.config.find_config_file: Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
docker.utils.config.find_config_file: No config file found
docker.utils.config.find_config_file: Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
docker.utils.config.find_config_file: No config file found
docker.utils.config.find_config_file: Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
docker.utils.config.find_config_file: No config file found
urllib3.connectionpool._make_request: http://localhost:None "GET /version HTTP/1.1" 200 835
urllib3.connectionpool._make_request: http://localhost:None "GET /v1.41/version HTTP/1.1" 200 835
compose.cli.docker_client.get_client: docker-compose version 1.27.4, build unknown
docker-py version: 4.4.1
CPython version: 3.7.3
OpenSSL version: OpenSSL 1.1.1d  10 Sep 2019
compose.cli.docker_client.get_client: Docker base_url: http+docker://localhost
compose.cli.docker_client.get_client: Docker version: Platform={'Name': 'Docker Engine - Community'}, Components=[{'Name': 'Engine', 'Version': '20.10.1', 'Details': {'ApiVersion': '1.41', 'Arch': 'arm', 'BuildTime': '2020-12-15T04:33:02.000000000+00:00', 'Experimental': 'false', 'GitCommit': 'f001486', 'GoVersion': 'go1.13.15', 'KernelVersion': '5.4.72-v7+', 'MinAPIVersion': '1.12', 'Os': 'linux'}}, {'Name': 'containerd', 'Version': '1.4.3', 'Details': {'GitCommit': '269548fa27e0089a8b8278fc4fc781d7f65a939b'}}, {'Name': 'runc', 'Version': '1.0.0-rc92', 'Details': {'GitCommit': 'ff819c7e9184c13b7c2607fe6c30ae19403a7aff'}}, {'Name': 'docker-init', 'Version': '0.19.0', 'Details': {'GitCommit': 'de40ad0'}}], Version=20.10.1, ApiVersion=1.41, MinAPIVersion=1.12, GitCommit=f001486, GoVersion=go1.13.15, Os=linux, Arch=arm, KernelVersion=5.4.72-v7+, BuildTime=2020-12-15T04:33:02.000000000+00:00
compose.cli.verbose_proxy.proxy_callable: docker inspect_network <- ('petnetfeederservice_default')
urllib3.connectionpool._make_request: http://localhost:None "GET /v1.41/networks/petnetfeederservice_default HTTP/1.1" 404 60
compose.cli.verbose_proxy.proxy_callable: docker containers <- (all=True, filters={'label': ['com.docker.compose.project=petnet-feeder-service', 'com.docker.compose.oneoff=False']})
urllib3.connectionpool._make_request: http://localhost:None "GET /v1.41/containers/json?limit=-1&all=1&size=0&trunc_cmd=0&filters=%7B%22label%22%3A+%5B%22com.docker.compose.project%3Dpetnet-feeder-service%22%2C+%22com.docker.compose.oneoff%3DFalse%22%5D%7D HTTP/1.1" 200 3
compose.cli.verbose_proxy.proxy_callable: docker containers -> (list with 0 items)
compose.cli.verbose_proxy.proxy_callable: docker containers <- (all=True, filters={'label': ['com.docker.compose.project=petnetfeederservice', 'com.docker.compose.oneoff=False']})
urllib3.connectionpool._make_request: http://localhost:None "GET /v1.41/containers/json?limit=-1&all=1&size=0&trunc_cmd=0&filters=%7B%22label%22%3A+%5B%22com.docker.compose.project%3Dpetnetfeederservice%22%2C+%22com.docker.compose.oneoff%3DFalse%22%5D%7D HTTP/1.1" 200 3
compose.cli.verbose_proxy.proxy_callable: docker containers -> (list with 0 items)
Attaching to 
pi@raspberrypi:/petnet-feeder-service $ 

**Also get this when trying to pull directly**

pi@raspberrypi:/petnet-feeder-service $ sudo docker pull tedder42/petnet-feeder-service
Using default tag: latest
latest: Pulling from tedder42/petnet-feeder-service
no matching manifest for linux/arm/v7 in the manifest list entries
pi@raspberrypi:~/petnet-feeder-service $

**from some other logs**
urllib3.connectionpool._make_request: http://localhost:None "POST /v1.41/images/create?tag=latest&fromImage=tedder42%2Fpetnet-feeder-service HTTP/1.1" 200 None
compose.cli.verbose_proxy.proxy_callable: docker pull -> <generator object APIClient._stream_helper at 0x7477a530>
latest: Pulling from tedder42/petnet-feeder-service
ERROR: compose.cli.main.main: no matching manifest for linux/arm/v7 in the manifest list entries
pi@raspberrypi:/petnet-feeder-service $

**Comment by tedder** [comment] 2021-01-01 19:17
@xoengine please use github markdown to format the logs and console text- it's really hard to read them. If you don't know how to do that, let me know.

**Comment by mbillow** [comment] 2021-01-02 01:02
Echoing @tedder, it’s difficult to read, but I do have some suggestions and follow-up questions. 

Are you using the compose file from the Wiki instructions or the README. I know it is confusing, but the Wiki is more up to date than the README. I just haven’t had the time to clean it up yet. You are running an ARMv7 device by the looks of your logs, so you will need to be using the `latest-arm7` or `latest-pib2` tag. There are pretty okay instructions in the Docker Compose file linked in the README. If following the instructions there don’t work, let us know!

**Comment by xoengine** [comment] 2021-01-02 03:27
Hi 

Sorry for the formatting, rookie mistake :-). I tried to fix it, hopefully that is better.  I was using the wiki "getting started" guide.  https://github.com/petnet-independence-project/petnet-feeder-service/wiki/Getting-Started

The compose file I used was in the "sample" directory from the code I pulled from the git repository.

My son said he got the webserver running by using the PI 2 rather than PI 3 image in the docket-compose file.  Not sure if that makes sense but it does look like it is running.

And now for the bummer part.  I thought I had a V2 as I don't have it that long but I guess after searching around it looks like I have a V1.  A packet capture does not show it doing any DNS lookups at all.  It is connecting out to ip address 44.239.255.181 on port 31314.

Is there any hope for V1 users or is it a lost cause?

**Comment by mbillow** [comment] 2021-01-02 03:51
Yup, what your son did is what I was suggesting. Unfortunately, we haven’t spent much time on the V1 feeders. Someone told me they verify the validity of the Electric Imp SSL certificates; haven’t verified myself because I have been trying to finish the stuff we have working on the V2s and don’t have access to a V1 personally. 

I can confirm though that 31314 is the port that the Electric Imp boards in the V1s use.

**Comment by mbillow** [comment] 2021-01-02 03:57
I know the whole point of this project is to revive feeders you already own, but you can buy V2 feeders for $30-35 NIB, shipped on eBay. 

https://www.ebay.com/itm/PETNET-SMARTFEEDER-2ND-GEN-WHITE-AUTOMATIC-PET-FEEDER-READ-DESCRIPTION-/114412788415

**Comment by tedder** [comment] 2021-01-23 05:23
FWIW I came across this same thing using 32-bit Raspbian on a Pi4, setting it to `tedder42/petnet-feeder-service`:
```
Pulling petnet-feeder-service (tedder42/petnet-feeder-service:latest)...
latest: Pulling from tedder42/petnet-feeder-service
ERROR: no matching manifest for unknown in the manifest list entries
```

It's more easily reproduced with vanilla docker:
```
$ docker pull tedder42/petnet-feeder-service:latest
latest: Pulling from tedder42/petnet-feeder-service
no matching manifest for unknown in the manifest list entries
```

I'm going to add v7l to the builds to :latest and see if that breaks things. I remember a conversation about this.

**Comment by tedder** [comment] 2021-01-23 05:44
chatting about this in Slack, I think `unknown` is the indicator that Docker is too dumb to know what architecture it should be on. Currently only amd64 and arm64 are in `latest`. I'm going to add v7l to it. If that works, that only leaves the Zero as the outlier (needing a different image). I'll test amd64, arm64, and arm32/v7l.

Marc on 2020-11-08:
> Backstory if you missed the thread: The docker cli doesn't have the logic to determine what version of ARM CPU the device is running and so it just pulls the ARM64 image by default. This makes ARMv6/7 devices like the Pi Zero, Zero W, etc. very unhappy and the container just segfaults. The Stackoverflow answer that lead me to this just says to pin to the right container hash... but that is inelegant and tedious if we have to keep updating our example docker-compose file.

related: https://raspberrypi.stackexchange.com/a/105045

**Comment by mbillow** [comment] 2021-02-13 23:19
@tedder Are you happy enough with where this ticket is to close it? I think we got a win from adding an additional arch to the `latest` tag, but ARMv <= 6 will likely always have to be its own tag.

**Comment by tedder** [comment] 2021-02-14 00:05
yep! I'm happy.

**Closed by tedder** 2021-02-14 00:05 UTC
